export const RULES = [
  'The game lasts 3 rounds.',
  'Nobody is eliminated.',
  'A new set of imposters is randomly selected each round.',
  'Everyone knows the general category.',
  'Normal players also know the secret word.',
  'Imposters know only the category.',
  'Imposters do not know who the other imposters are during clue giving.',
  'Go around the room once.',
  'Each person gives exactly one clue.',
  'A clue may contain no more than 2 words.',
  'A clue cannot repeat a clue already used that round.',
  'A clue cannot contain the secret word or part of the secret word.',
  'No spelling hints, initials, rhyming hints, “starts with…”, or similarly direct hints.',
  'Normal players try to prove they know the word without making it obvious to the imposters.',
  'Imposters bluff using the category and clues they hear.',
  'After everyone gives a clue, discussion begins.',
  'Discussion lasts exactly 2 minutes.',
  'Players may accuse, defend, and discuss clues during that period.',
  'Nobody may explicitly say the secret word during discussion.',
  'When time expires, everyone votes for one suspected imposter.',
  'A player may not vote for themselves.',
  'The person with the most votes reveals whether they are an imposter.',
  'A tied vote results in a runoff between the tied players.',
  'Nobody leaves the game after voting.',
  'After the vote, all imposters reveal themselves.',
  'The imposters receive one collective guess at the secret word.',
  'Then the next round begins with newly randomized imposters.',
]
