export const RULES = [
  'The game lasts 3 rounds. Nobody is eliminated.',
  'A new set of imposters is randomly selected each round.',
  'The number is automatic: 1–11 players gets 1 imposter, 12–16 gets 2, and 17+ gets 3.',
  'Everyone knows the category. Normal players also know the secret word; imposters do not.',
  'Go around once. Each person gives exactly one clue of no more than 2 words.',
  'Do not repeat a clue or use the word, part of it, spelling hints, initials, rhymes, or “starts with” hints.',
  'After clue giving, the host starts the 2-minute discussion.',
  'After discussion, the host opens voting in the app.',
  'Each player privately selects one person they believe is an imposter.',
  'You cannot vote for yourself, and each player gets one secret vote.',
  'If the highest vote is tied, only the tied players appear in a runoff vote.',
  'The selected player is revealed as either an imposter or a normal player.',
  'Nobody is eliminated.',
  'After the vote result, all imposters reveal themselves.',
  'The imposters receive one collective guess at the secret word.',
  'Player pages update automatically as the host advances the game.',
]
